version: '2'

services:
    app:
        build: .
        container_name: stephencoakley.local
        networks:
            - proxy
        restart: on-failure

networks:
    proxy:
        external:
            name: proxy
