name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker image
        run: |
          export TAG=${GITHUB_SHA:0:8}
          docker-compose build

      - name: Push Docker image
        run: |
          export TAG=${GITHUB_SHA:0:8}

          echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin
          docker-compose push
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Update deployment config
        run: sed -i s/:latest/:${GITHUB_SHA:0:8}/ config/deployment.yaml
        if: github.ref == 'refs/heads/master'

      - name: Get cluster configuration
        uses: digitalocean/action-doctl@master
        if: github.ref == 'refs/heads/master'
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show nyc1 > .kubeconfig

      - name: Deploy
        uses: docker://lachlanevenson/k8s-kubectl
        if: github.ref == 'refs/heads/master'
        with:
          args: --kubeconfig=.kubeconfig apply -f config/deployment.yaml
